[package]
name = "guessing-game"
version = "0.1.0"
authors = ["Georgios Angelopoulos <georgios.angelopoulos@ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
